# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RN048_cocoapods' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN048_cocoapods

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
  ]
  pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'

end

target 'RN048_cocoapods-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RN048_cocoapods-tvOS

  target 'RN048_cocoapods-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
